# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master

name:  $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]

pool:
  vmImage: 'Ubuntu-18.04'

variables:
  CURRENT_DATE: $[format('{0:yyyyMMdd\-HHmmss}', pipeline.startTime)]
  REPOSITORY_NAME: $(Build.Repository.Name)
  COMMIT_TAG: $(git log --format=%h -1)

steps:
- script: |
    curl -L https://cdn.discordapp.com/attachments/283769550611152897/615767904926826498/lzss -o lzss
    sudo chmod +x lzss
  displayName: 'Get lzss'
  
- script: |
    docker run -v `pwd`:`pwd` -w `pwd` devkitpro/devkitarm 'sudo mv lzss /opt/devkitpro/tools/bin && make package-nightly'

    echo '##vso[task.setvariable variable=COMMIT_TAG]'$(git log --format=%h -1)
    echo '##vso[task.setvariable variable=COMMIT_MESSAGE]'$(git log --pretty=format:"%an - %s" -1)
  displayName: 'Build nds-bootstrap'

- script: |
    mkdir bin/TWiLightMenu/
    printf $(COMMIT_TAG) >> bin/TWiLightMenu/nightly-bootstrap.ver
    mv bin/ nds-bootstrap/
    7z a nds-bootstrap.7z nds-bootstrap/
    cp nds-bootstrap.7z $(Build.ArtifactStagingDirectory)/nds-bootstrap.7z
  displayName: 'Pack 7z package'

